name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: armin-panahi

          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=F7D774&color_dots=#ebedf0,#d6c47a,#c8b25a,#b89d35,#F7D774
            dist/github-contribution-grid-snake-dark.svg?color_snake=F7D774&color_dots=#161B22,#4E4420,#8F7A2A,#C8A83A,#F7D774
      
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
